package pages;

import dao.PlayerDao;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Player;
import models.Tournament;

public class AjoutParticipant extends javax.swing.JPanel {
    static Tournament tournois;

    public AjoutParticipant(Tournament tournois) {
        initComponents();
        this.tournois = tournois;

        // Style des champs
        Color fieldBg = Color.decode("#52B960");
        Color fieldFg = Color.decode("#FCFFFC");
        pseudo_tf.setBackground(fieldBg);
        pseudo_tf.setForeground(fieldFg);
        email_tf.setBackground(fieldBg);
        email_tf.setForeground(fieldFg);
        platforme_tf.setBackground(fieldBg);
        platforme_tf.setForeground(fieldFg);

        // Champ équipe masqué pour tournoi solo
        team_tf.setVisible(false);
    }

    private boolean validateField() {
        String pseudo = pseudo_tf.getText().trim();
        String email = email_tf.getText().trim();
        LocalDate birthDate = birthDate_dpk.getSelectedDate();
        String platforme = platforme_tf.getText().trim();

        if (pseudo.isEmpty()) {
            showError("Le pseudo est obligatoire.");
            return false;
        }
        if (email.isEmpty() || !email.contains("@")) {
            showError("L'email est obligatoire et doit être valide.");
            return false;
        }
        if (birthDate == null) {
            showError("La date de naissance est obligatoire.");
            return false;
        }
        if (platforme.isEmpty()) {
            showError("La plateforme est obligatoire.");
            return false;
        }
        return true;
    }

    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthDate_dpk = new swing.MyDatePicker();
        jLabel1 = new javax.swing.JLabel();
        platforme_tf = new swing.MyTextField();
        team_tf = new swing.MyTextField();
        button1 = new swing.Button();
        button2 = new swing.Button();
        pseudo_tf = new swing.MyTextField();
        email_tf = new swing.MyTextField();

        setBackground(java.awt.SystemColor.control);
        setForeground(java.awt.SystemColor.control);
        setOpaque(false);

        birthDate_dpk.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(122, 140, 141));
        jLabel1.setText("Date de naissance");
        jLabel1.setIconTextGap(6);

        platforme_tf.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        platforme_tf.setForeground(new java.awt.Color(102, 102, 102));
        platforme_tf.setText("Platforme");

        team_tf.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        team_tf.setForeground(new java.awt.Color(102, 102, 102));
        team_tf.setText("Equipe");
        team_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team_tfActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(102, 255, 102));
        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setText("Valider");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 0, 51));
        button2.setText("Annuler");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        pseudo_tf.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        pseudo_tf.setText("Pseudo");

        email_tf.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        email_tf.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthDate_dpk, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(email_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pseudo_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(team_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(platforme_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pseudo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthDate_dpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(platforme_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(team_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String pseudo = pseudo_tf.getText().trim();
        String email = email_tf.getText().trim();
        LocalDate dateNaiss = birthDate_dpk.getSelectedDate();
        String platforme = platforme_tf.getText().trim();

        if (!validateField()) return;

        try {
            Player player = new Player(pseudo, email, dateNaiss, platforme, tournois.getId());
            PlayerDao.addPlayerToTournament(player); // Pas d'équipe en solo !
            JOptionPane.showMessageDialog(this, "Participant ajouté avec succès !");
            vider();
        } catch (SQLException | ClassNotFoundException ex) {
            showError("Erreur : " + ex.getMessage());
            Logger.getLogger(AjoutParticipant.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        vider();
    }//GEN-LAST:event_button2ActionPerformed

    private void team_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team_tfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyDatePicker birthDate_dpk;
    private swing.Button button1;
    private swing.Button button2;
    private swing.MyTextField email_tf;
    private javax.swing.JLabel jLabel1;
    private swing.MyTextField platforme_tf;
    private swing.MyTextField pseudo_tf;
    private swing.MyTextField team_tf;
    // End of variables declaration//GEN-END:variables

    private void vider() {
        pseudo_tf.setText("");
        email_tf.setText("");
        platforme_tf.setText("");
//        birthDate_dpk.clear(); // À implémenter dans MyDatePicker si besoin
    }
}
