/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages;

/**
 *
 * @author RT
 */
import dao.DatabaseService;
import models.Tournament;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;

public class MiseAJour extends javax.swing.JPanel {
    
    private JTextField nameField;
    private JTextArea descriptionField;
    private JTextField startDateField;
    private JTextField endDateField;
    private JButton updateButton;
    private Tournament tournament;

    /**
     * Creates new form MiseAJour
     */
    public MiseAJour() {
        this.tournament = tournament;
        initializeComponents();
        fillFormWithTournament();
    }
     private void initializeComponents() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(8, 8, 8, 8);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Nom
        gbc.gridx = 0; gbc.gridy = 0;
        add(new JLabel("Nom du tournoi:"), gbc);
        nameField = new JTextField(20);
        gbc.gridx = 1;
        add(nameField, gbc);

        // Description
        gbc.gridx = 0; gbc.gridy = 1;
        add(new JLabel("Description:"), gbc);
        descriptionField = new JTextArea(3, 20);
        JScrollPane descScroll = new JScrollPane(descriptionField);
        gbc.gridx = 1;
        add(descScroll, gbc);

        // Date de début
        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("Date de début (YYYY-MM-DD):"), gbc);
        startDateField = new JTextField(10);
        gbc.gridx = 1;
        add(startDateField, gbc);

        // Date de fin
        gbc.gridx = 0; gbc.gridy = 3;
        add(new JLabel("Date de fin (YYYY-MM-DD):"), gbc);
        endDateField = new JTextField(10);
        gbc.gridx = 1;
        add(endDateField, gbc);

        // Bouton enregistrer
        updateButton = new JButton("Enregistrer");
        gbc.gridx = 0; gbc.gridy = 4; gbc.gridwidth = 2;
        add(updateButton, gbc);

        updateButton.addActionListener(e -> updateTournament());
    }
     
     private void fillFormWithTournament() {
        if (tournament != null) {
            nameField.setText(tournament.getName());
            descriptionField.setText(tournament.getDescription());
            startDateField.setText(tournament.getStartDate() != null ? tournament.getStartDate().toString() : "");
            endDateField.setText(tournament.getEndDate() != null ? tournament.getEndDate().toString() : "");
        }
    }
     
     private void updateTournament() {
        String name = nameField.getText().trim();
        String description = descriptionField.getText().trim();
        String start = startDateField.getText().trim();
        String end = endDateField.getText().trim();

        if (name.isEmpty() || start.isEmpty() || end.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nom, date de début et date de fin sont obligatoires.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            LocalDate startDate = LocalDate.parse(start);
            LocalDate endDate = LocalDate.parse(end);

            // Mettre à jour les données dans l'objet
            tournament.setName(name);
            tournament.setDescription(description);
            tournament.setStartDate(startDate);
            tournament.setEndDate(endDate);

            // Mettre à jour en base de données
            DatabaseService.executeUpdate(
                "UPDATE tournaments SET name = ?, description = ?, start_date = ?, end_date = ? WHERE id = ?",
                name, description, startDate, endDate, tournament.getId()
            );

            JOptionPane.showMessageDialog(this, "Tournoi mis à jour avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Format de date invalide. Utilisez YYYY-MM-DD.", "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
